services:
  server:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      CONFIG_PATH: /app/config/config.yaml
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_SSL_MODE: disable
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: