// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/proto/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParametersJson *structpb.Struct       `protobuf:"bytes,2,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_pkg_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Filter) GetParametersJson() *structpb.Struct {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_pkg_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskMessage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TaskMessage) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_pkg_proto_task_proto protoreflect.FileDescriptor

const file_pkg_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/task.proto\x12\x04task\x1a\x1cgoogle/protobuf/struct.proto\"^\n" +
	"\x06Filter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12@\n" +
	"\x0fparameters_json\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0eparametersJson\"Y\n" +
	"\vTaskMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12$\n" +
	"\x06filter\x18\x03 \x01(\v2\f.task.FilterR\x06filterB*Z(media-processing-platform/pkg/proto;taskb\x06proto3"

var (
	file_pkg_proto_task_proto_rawDescOnce sync.Once
	file_pkg_proto_task_proto_rawDescData []byte
)

func file_pkg_proto_task_proto_rawDescGZIP() []byte {
	file_pkg_proto_task_proto_rawDescOnce.Do(func() {
		file_pkg_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_task_proto_rawDesc), len(file_pkg_proto_task_proto_rawDesc)))
	})
	return file_pkg_proto_task_proto_rawDescData
}

var file_pkg_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_task_proto_goTypes = []any{
	(*Filter)(nil),          // 0: task.Filter
	(*TaskMessage)(nil),     // 1: task.TaskMessage
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_pkg_proto_task_proto_depIdxs = []int32{
	2, // 0: task.Filter.parameters_json:type_name -> google.protobuf.Struct
	0, // 1: task.TaskMessage.filter:type_name -> task.Filter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_task_proto_init() }
func file_pkg_proto_task_proto_init() {
	if File_pkg_proto_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_task_proto_rawDesc), len(file_pkg_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_task_proto_goTypes,
		DependencyIndexes: file_pkg_proto_task_proto_depIdxs,
		MessageInfos:      file_pkg_proto_task_proto_msgTypes,
	}.Build()
	File_pkg_proto_task_proto = out.File
	file_pkg_proto_task_proto_goTypes = nil
	file_pkg_proto_task_proto_depIdxs = nil
}
